### ISSUE TITLE
Blocks randomly appear inside chunks which have been populated only with stone

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#1]
I've observed that certain blocks will randomly appear in random locations inside the chunks. Obviously, this shouldn't happen—most of these blocks don't even have ID mappings yet in the server. I have no idea what causes this issue.

The following blocks have been seen so far:
- Diamond ore
- Gold ore
- Iron ore
- Diamond block
- Emerald block
- Grey clay

**Comment by caelunshun** [comment]
Need to confirm that this still happens after the architecture rewrite.

**Comment by caelunshun** [comment]
Confirmed that this still happens.

**Comment by caelunshun** [comment]
Again need to confirm that this still happens - pretty much everything has been rewritten since this issue was opened.

**Comment by amberkowalski** [comment]
Closing - Outdated
