### ISSUE TITLE
Support weather: rain, snow, thunder

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#131]
This includes:
* Loading current weather from level.dat and sending it to clients.
* Changing weather and sending the updates to clients.
* Depending on the biome at a given location, occasionally spawn snow at a top block when it is snowing.
* During a thunderstorm, occasionally spawn lightning. (The fire from lightning is a separate issue.)

**Comment by Defman** [comment]
- Rain last for [0.5;1] days
- Clear weather last for [0;7] + 0.5 days
- Thunderstorm, not sure how they work? Might be chance that rain is a thunderstorm, or thunderstorm might be on its own counter such that rain can turn into thunder after it already started.

- Lightning during a thunderstorm, pick some random number of loaded chunks and summon global lightning entity and emit it for all players within 512 blocks radius
- Snow during rain/thunderstorm within cold biomes, pick some random number of loaded chunks and try to spawn if it's cold enough.
- During rain put out fires

The level data includes 4 fields
- raining
- rain_time
- thundering
- thunder_time

If rain and thundering are implemented as two separate weather events such that thunder overwrites rain. This will allow normal rain to turn into a thunderstorm and thunderstorm to turn into rain.

**Comment by Defman** [comment]
Should be closed in favor of #184

**Comment by caelunshun** [comment]
Implemented by #182
