### ISSUE TITLE
Store highest solid block in Chunk for each column of blocks

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#133]
It is going to become frequent that we need to know the highest solid block in a column, e.g. for #131. The chunk implementation should cache this value to improve the performance of doing this.

**Comment by OvermindDL1** [comment]
Also recall that the cache can hold a couple of different values.  There is a 'top-most' for solid opaque blocks (roofs), a top-most for solid transparent blocks (trees, glass), a 'top-most' for any block (a torch), each of which are used in different ways and times, at least in the official engine.

**Comment by Defman** [comment]
#181

**Comment by Defman** [comment]
Should be closed in favor of #183
