### ISSUE TITLE
Chunk section corruption when sending to client

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#147]
![2019-10-02_21 50 10](https://user-images.githubusercontent.com/25177429/66098140-af2a9200-e55e-11e9-8bc3-b853d71b9091.png)
Seems like there are issues sending light for certain chunks. This bug only exists after the Tokio rewrite; previous commits are unaffected.

**Comment by caelunshun** [comment]
Looks like this is actually caused by entire sections somehow not being sent or received correctly.

**Comment by caelunshun** [comment]
Oddly enough, I am no longer able to reproduce this. Can anyone else confirm?

**Comment by ColdIce1605** [comment]
Chunks do not relight,
Effected chunks do hold incorrect time values even if relit to correct light values
unloaded chunks get effected by the bug
new chunks sometimes

latest feather
everything in the list is a symptom, might help find the root cause
