### ISSUE TITLE
Parallelize the chunk worker

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#150]
Currently, any requests to the chunk worker are blocking, so chunk saving causes visible lag spikes in chunk load performance when a player is flying around. The worker should be parallelized so that separate chunk loads/saves are performed on a thread pool.

`RegionHandle` will have to be updated to allow for concurrent reading from the file, likely by locking the `SectorAllocator` and then having a separate lock for each individual chunk in the region. The code will have to be checked thoroughly so as to avoid region file corruption using this technique.

**Comment by ccgauche** [comment]
If we use a RWLock we can lock it while adding a chunk (We compute all chunk load and after add the chunk) and we can save chunks in another thread without needing to lock the whole system.
