### ISSUE TITLE
Lava buckets place water

### ISSUE THREAD

**Issue by Ethan-Xd** [feather-rs/feather#157]
![image](https://user-images.githubusercontent.com/24442053/66267999-dbaf1880-e894-11e9-8ba1-ccd9eeca6d9b.png)

On the left is what a bucket of water places. On the right is what a bucket of lava places. Strangely, the right liquid is opaque, gives off light, and still makes lava sounds. I am not using any resource packs.

(Also, liquid physics don't seem to work correctly as reported in this release?)

**Comment by caelunshun** [comment]
Yes, this issue has existed for a while. Probably the client expects us to send some sort of block update to tell them about the liquid, but Feather doesn't yet have support for buckets/liquids.

> (Also, liquid physics don't seem to work correctly as reported in this release?)
Sorry, that was worded somewhat poorly—entities now slow down when going through liquids, but liquid physics are not implemented yet.

**Comment by amberkowalski** [comment]
Closed - Outdated
