### ISSUE TITLE
General guidelines and structure of the project

### ISSUE THREAD

**Issue by Defman** [feather-rs/feather#194]
There should exist a general set of guidelines such that the project is coherent. I'm not sure what such guidelines/rules should consist of...

**Comment by Defman** [comment]
Furthermore, should features of Minecraft be hidden behind feature flags such that it is possible to compile feather without block placement, chat, entity AI and or etc. Such that its possible to obtain a stripped-down version to be used as a hight performance lobby? That would also encourage some modularity to the structure of the project.

**Comment by ccgauche** [comment]
This is a very good idea if it can be added in practice I think a configuration file at startup can also do the job by not executing the part of the code responsable for a specific action like block updates ...
It is not possible in the Java version without really changing the code at NMS level but with legion and ECS modularity It can probably be added without even rewritting all the code of feather.

**Comment by caelunshun** [comment]
Do you mean guidelines on a technical level or a community level? I'm certainly open to making these, but I'm not sure exactly what this entails.

**Comment by Defman** [comment]
Guidelines on a technical level, I wanted to come with suggestions but wanted a more open discussion. My thought is that the guidelines should keep the project somewhat structured and coherent across multiple contributors, such that it is easier to start developing and contributing.
- What should be its own crate?
- What is core and what's not?
- How should we structure the systems?
- 80 col documentation and or line width?
- ... and many more nuances of programming.

**Comment by onbjerg** [comment]
A general tour of the existing code base would also be appreciated

**Comment by amberkowalski** [comment]
Closed - Newer issue opened
