### ISSUE TITLE
Chunk sections are not correctly loaded.

### ISSUE THREAD

**Issue by ccgauche** [feather-rs/feather#201]
Some chunk sections are not loaded properly and saved into the map as empty so through each restart the map as more and more holes of size 16x16x16
![image](https://user-images.githubusercontent.com/16625987/80598539-d16b8c00-8a29-11ea-9cd1-da7996ea621b.png)
![image](https://user-images.githubusercontent.com/16625987/80598574-df211180-8a29-11ea-9177-74ecdb658bb2.png)

**Comment by caelunshun** [comment]
Interesting, might be related to #147. I'll take a look, thanks for reporting!

**Comment by caelunshun** [comment]
Having trouble reproducing this issue—could you provide the world save? A few other questions:

* What OS is this?
* Does it only happen after the server restarts?
* How many players were online?

**Comment by besuper** [comment]
I was on windows with wsl (debian) and it's happen when I restart the server I guess (maybe when the server crash?). I think we care about players in this case but we was 2.
[world.zip](https://github.com/feather-rs/feather/files/4554661/world.zip)

**Comment by amberkowalski** [comment]
Closed - Outdated
