### ISSUE TITLE
Player count is not correct

### ISSUE THREAD

**Issue by ccgauche** [feather-rs/feather#202]
Player count is not correct! More player can connect than the maximum
https://media.discordapp.net/attachments/542023114477797400/705040061099671642/unknown.png

**Comment by caelunshun** [comment]
Thanks for reporting, should be a trivial fix.

**Comment by besuper** [comment]
Max players is fixed but the player count is still not updated correctly. (Players count is not decreased on quit)

**Comment by caelunshun** [comment]
@besuper fixed, thanks
