### ISSUE TITLE
LaTeX inspired text parsing

### ISSUE THREAD

**Issue by Defman** [feather-rs/feather#208]
I propose defining a small markup language inspired by lisp, such that we can easily define Raw Json text in our config files.
```
token     ::= text|closure|list|atom
delimiter ::= space|newline
text      ::= '"' (atom)delmiter* '"'
atom      ::= (char|number)*
closure   ::= '(' (atom)delimiter+')'
list      ::= '[' (atom)delimiter* ']'
```

It would allow us to write the following text definition in our config files

```
[
  (red some red text)
  (blue some blue text)
  (hover (entity (text some long text) zombie id)
  (text you can't do that dave)
  "you can't do that dave"
]
```

Where `"string message"` is sugar for `(text string message)`,
and `["element a" "element b" ...]` is sugar for `(list "element a" "element b" ...)`

alternatively, we could implement a "Haskell" version, which would just omit pretences for the first call, ie.
```
[
  red some red text,
  blue some blue text,
  hover (entity (text some long text) zombie id,
  text you can't do that dave,
  "you can't do that dave"
]
```

However, the comma would become ambiguous when pretences are omitted in the list notation.

**Comment by ccgauche** [comment]
&<color> color format is used everywhere for is compactness, simplicity...
Some people can argue that this format is hard to read for new-comers so I would be nice that feather supports a fully-featured format for complex cases like hovers, click events... but that we can mix in it the ancient format!
```
(red This text is in red but (dark-green this one is in green!))
```

Could be written:
```
&cThis text is in red but &2This one is in green!
```

If you know the table it is so easy and clean to write.
PS: People that come from bukkit development or have a bukkit server know this table because it is used everywhere.
If this is not added into feather plugin developers are going to use an external crate to do that or do they own implementation of that.

**Comment by Defman** [comment]
I don't think we should discourage the usage of Minecraft deprecated text markup language. And I think we should do one of the following.
1. Let an extern crate implement it, for those who have a need for it.
2. Implement it but mark it as deprecated and promote the Text API or the lisp syntax over it.

**Comment by caelunshun** [comment]
Consensus as per the Discord discussion:

* Implement a LaTeX-inspired text format using `@` as the escape character. Example: 
```
@red{this is red text} @green{this is green @gold{and this is gold} but this is still green.}
```
* Prior to Feather 1.0, initiate a poll to determine whether we support the legacy format (&<code>).

**Comment by Defman** [comment]
We could choose to implement latex with `\` since toml has single-quoted strings, and we should use toml for config files.

**Comment by Defman** [comment]
One issue I have with the LaTeX version is currying since LaTeX versions have two kinds arguments `{}` and `[]` it would be hard to define currying.

**Comment by Defman** [comment]
Another option would to implement the builder pattern and operator overloader pattern inteperator.
```
"Some white bold text".white().bold()
```
and
```
"Some white bold text" * Color::White * Style::Bold
```
Which is exactly the same syntax used for the TextAPI.

**Comment by Defman** [comment]
A LaTeX inspired functional markup language

```
@bold this is some bold text @red this text is bold and red @italic {this text is bold red and italic} this is bold and italic @color #FFFFFF bold white text
```

The syntax is quite straight forward
```
bold :: Token* -> Text
color :: Color -> Token* -> Text
red :: Token* -> Text
```

Is a quite simple language where `Token*` is the remaining input, this can be limited by `{}`.

**Comment by Defman** [comment]
I would like to define more precisely what I think the language should be cable of and what use cases it should support.

1. The language should be implemented in three steps, lexing, parsing, and interpreting.
2. The interpreting should be exposed as a replaceable service, such to allow plugins to overwrite the functionality and extend the default interpreter.

```
LexToken = StartScope | EndScope | Call(String) | Word(String) | Space(String)
ParsedToken = Scope([ParsedToken]) | Call(String) | Word(String) | Space(String)
Literal = Word(String) | Space(String) | Type(String, Literal)
```

The literal `Type` act as a way to tag words, ie `Type("bool", Word("true"))` such that types and literals do not need to be predefined. Interpreters can choose to implement their own literals in their implementation the tagging as a string is an example.

The language and parsing should be separated from the interpretation, such that we can allow plugins to change the evaluation. This would allow the addition of functions like `@username` and more complex interpreters might choose to implement branching like `@true \a \b -> a` and `@false \a \b -> b`. A quick example of this
```
@eq @username {The_Defman} {@red @username} {@blue @username}
```
