### ISSUE TITLE
Error when connecting with non-licenced version of Minecraft

### ISSUE THREAD

**Issue by DuckerMan** [feather-rs/feather#215]
![image](https://user-images.githubusercontent.com/23637939/81389434-7f5df100-9122-11ea-990f-b0b842f8cc93.png)
I know about `online-mode`, but I think you should add message like "Auth failed" instead of error

**Comment by Defman** [comment]
PR #216 solves this issue with "Failed to verify username!" for release mode only.

**Comment by caelunshun** [comment]
Thanks for reporting; the bug's been fixed!

**Comment by DuckerMan** [comment]
Thanks for fast reaction, guys :)
