### ISSUE TITLE
Update MC implementation from 1.13.2 to 1.16.2

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#220]
Here are the main changes in 1.15/1.14 which will affect us:
* Biomes are now 3D
* Chunks now store one section above and below `[0, 255]` for lighting purposes
* Lighting is now sent in a separate packet from `Chunk Data`, and it appears lighting updates are now sent to clients (previously, the server and client would each handle lighting on their own)

#307

**Comment by fionera** [comment]
What about implementing support for multiple Version?

**Comment by caelunshun** [comment]
> What about implementing support for multiple Version?

This is a separate issue: #25. It's not high priority right now, and it will take a lot of work to implement. In the future, if the demand is high enough, we may add multiversion support.
