### ISSUE TITLE
Place Directional Blocks Properly

### ISSUE THREAD

**Issue by nikhiljha** [feather-rs/feather#222]
Blocks that can be placed at different angles always get placed facing north.

![stairs](https://user-images.githubusercontent.com/2773700/81878609-66e44100-953d-11ea-87b6-aaa2cda132d2.gif)

**Comment by caelunshun** [comment]
Closely related to #177

**Comment by ssttevee** [comment]
This was resolved with #241

**Comment by AnEthernetCable** [comment]
This is still an issue with all rail blocks / types
