### ISSUE TITLE
Crash when block is destroyed at height 256

### ISSUE THREAD

**Issue by Seadragon91** [feather-rs/feather#226]
Server crashed when a block is destroyed at height 256:
`thread '<unnamed>' panicked at 'assertion failed: y < CHUNK_HEIGHT', core/chunk/src/lib.rs:333:9`

**Comment by Defman** [comment]
@caelunshun is `.filter(|pos| pos.y >= 0 && pos.y <= 256)` (`server/lighting/src/lib.rs:514`) also true for version 1.13? Since this cause the line `442` to try and find a light source at `256` which is above the build limit.

**Comment by Defman** [comment]
#227

**Comment by caelunshun** [comment]
Thanks for reporting!
