### ISSUE TITLE
The server crashes when using a Bow

### ISSUE THREAD

**Issue by Rheydskey** [feather-rs/feather#263]
Hey, guys,
So when I used my bow, the arrow shot crashed the server. 
Here's the error: 
thread 'feather' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfBounds(27, Main)', server/player/src/packet_handlers/digging.rs:479:34

PS: English is not my native language

**Comment by Defman** [comment]
This has already been noticed and is being fixed... cant quite find the PR, but was left as a note.

```rust
// Wrong
0..=27

// Correct
0..27
```

Thanks

**Comment by Schuwi** [comment]
I couldn't find a PR for this but I had already fixed it, just didn't open a PR yet, so here it is now.
