### ISSUE TITLE
Fix LICENSE.md

### ISSUE THREAD

**Issue by Schuwi** [feather-rs/feather#268]
The project is currently `Copyright [yyyy] [name of copyright owner]` as per LICENSE.md. You should probably fix that and name a copyright owner @caelunshun

**Comment by caelunshun** [comment]
From what I know, that section is part of the appendix and describes how the license should be applied as a comment at the top of a source file. It's not intended that the year and copyright owner fields be replaced within the license file itself. 

So the question here is whether that header should be applied to all source files—which is presently not the case. I'm not sure if it's a requirement or not, but personally I prefer avoiding polluting each file with a license header.

**Comment by Schuwi** [comment]
Yeah, I see. I did some research and read the license multiple times, so apparently there are `Contributor`s and a `Licensor` (who is also a `Contributor`).
The `Licensor` (individual or legal entity yada yada) is the copyright holder and the one who grants the License. So basically the entity named in that Appendix. A `Contributor` is providing their `Work` to the `Licensor` according to the License.
So basically everyone keeps their copyright but grants unrestricted irrevocable usage rights to everyone, kinda. I was mistaken about that before as I thought everyone would just transfer their copyrights to the License holder.
Still this `Licensor` needs to be named somewhere and it must be made clear that every file in the repo is licensed per this license.

    "Work" shall mean the work of authorship, whether in Source or Object form, made available under the License, as indicated by a copyright notice that is included in **or attached to the work** (an example is provided in the Appendix below).
(emphasis mine)
So adding something like this to the README should be fine(and maybe removing that appendix from LICENSE.md to make it cleaner):

 License:

Unless explicitly stated otherwise all files in this repository are licensed under the Apache Software License 2.0 [insert appendix with copyright owner here]

I am in no way knowledgeable in legal stuff but all of the above can be inferred from the license text itself.
