### ISSUE TITLE
Invalid server icon (unknown format)

### ISSUE THREAD

**Issue by skillman623** [feather-rs/feather#274]
Pinging using vanilla 1.13.2 client.
Server icon (favicon) is a unknown format.
This should be a base64 (64x64) png file. Example is below:
![server-icon](https://user-images.githubusercontent.com/29513384/86540945-4b0e7300-bece-11ea-8cae-3e4a908d9215.png)

Please refer to https://wiki.vg/Server_List_Ping#Response for more details.

**Comment by skillman623** [comment]
Sorry, I was mistaken. Looking closer at the code the server sends a blank favicon instead of dropping that part of the response. 
While pinging to the server, the client console throws an error; unknown format. The reason for this is because in feather the response in the handshake without a favicon is different from vanilla (see below).
**Feather**

> packet = Some(StatusResponse(StatusResponse { status: "{\"description\":{\"text\":\"A Feather server\"},\"favicon\":\"\",\"players\":{\"max\":16,\"online\":0},\"version\":{\"name\":\"Feather 1.13.2\",\"protocol\":404}}" }))

**Vanilla 1.12.2**(without a favicon)

> packet = Some(StatusResponse(StatusResponse { status: "{\"description\":{\"text\":\"1.12.2\"},\"players\":{\"max\":2,\"online\":0},\"version\":{\"name\":\"1.12.2\",\"protocol\":340}}" }))

**Comment by caelunshun** [comment]
> Sorry, I was mistaken. Looking closer at the code the server sends a blank favicon instead of dropping that part of the response.
> While pinging to the server, the client console throws an error; unknown format. The reason for this is because in feather the response in the handshake without a favicon is different from vanilla (see below).
> **Feather**
> 
> > packet = Some(StatusResponse(StatusResponse { status: "{"description":{"text":"A Feather server"},"favicon":"","players":{"max":16,"online":0},"version":{"name":"Feather 1.13.2","protocol":404}}" }))
> 
> **Vanilla 1.12.2**(without a favicon)
> 
> > packet = Some(StatusResponse(StatusResponse { status: "{"description":{"text":"1.12.2"},"players":{"max":2,"online":0},"version":{"name":"1.12.2","protocol":340}}" }))

Ah, makes sense. Thanks for investigating this!

From what I can tell, the solution is to not send any favicon field when the server icon file is missing?

**Comment by skillman623** [comment]
I believe so, yes.
