### ISSUE TITLE
Skip saving chunks that have not been modified

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#278]
#276 removes the modification check before saving chunks, which means all loaded chunks will be saved when world saving is performed. This will scale poorly to large numbers of chunks, so a new, revised check should be added that avoids the entity-related problems discussed in #275.

A possible solution would be to track entity spawns and chunk crosses and mark chunks as modified whenever an entity crossed into or out of a chunk.

**Comment by Schuwi** [comment]
Hmm yeah that could actually be an easy fix - just mark the old chunk of a ChunkCrossEvent as modified and put the old check back in.
I'll take a look and add it to the PR if viable.

**Comment by Schuwi** [comment]
This was resolved in #276
