### ISSUE TITLE
Crash when placing above build limit

### ISSUE THREAD

**Issue by AnEthernetCable** [feather-rs/feather#292]
Placing any block above the build limit of the game will cause the server to crash with the following:
```thread 'feather' panicked at 'called `Option::unwrap()` on a `None` value', server/player/src/packet_handlers/placement.rs:124:29```

This is as of commit `5e22d74` on Jul 31, 2020
Built and tested on Pop OS 20.04 + Linux kernel 5.4.0-7634-generic

**Comment by Schuwi** [comment]
Thanks! #294 should fix this
