### ISSUE TITLE
Doors do not place correctly

### ISSUE THREAD

**Issue by AnEthernetCable** [feather-rs/feather#293]
Only the bottom section of doors are placed when trying to place a door. The top section of the door drops a door item. See image below:
![image](https://user-images.githubusercontent.com/26227270/89745465-a9a0b100-da79-11ea-982c-7fa543d0ef64.png)
This is as of commit `5e22d74` on Jul 31, 2020
Built and tested on Pop OS 20.04 + Linux kernel 5.4.0-7634-generic

**Comment by Schuwi** [comment]
Good catch! Missed some of those double-block types like doors and tall grass when implementing block support checks. I'll see to getting it fixed

**Comment by PonasKovas** [comment]
Another issue with doors:
sometimes when you place them on grass with snow, the block doesn't change and still is snowy
![screenshot20200815122411](https://user-images.githubusercontent.com/25486263/90309609-b8acb680-def2-11ea-9ab4-b36fec91b84b.png)

**Comment by Schuwi** [comment]
@PonasKovas Could you open a new issue for this please? As far as I can tell this should also happen with blocks other than doors right now

**Comment by Schuwi** [comment]
Update on the fix for this issue: It's not as trivial as I initially thought.
These multi-block structures are a real pain in the bottom and I haven't even considered them when implementing the block support checks. The problem occurs when assuring the blocks are supported upon placement. As neither of the block halves are supported without the other I can't check for support without placing one of them first, without knowing whether it'd be supported there, potentially having to revert that block change if the support check turns out false, which is all kinds of hacky and bad.
I'll have to think about it a bit more, probably have to do some design tweaks in the whole block support interface.

**Comment by Protonull** [comment]
Some testing on the latest commit 9539a21c9c0fbe681ec1e8851519280438dd583f shows that placing a door will replace whatever was above the bottom door block.
![door_bug](https://user-images.githubusercontent.com/52572989/103447984-b1602c80-4c8a-11eb-9ec1-6d0ce7f0ed70.gif)

**Comment by Stoozy** [comment]
@Schuwi Hello, I am a new contributor and have done a basic fix. There may still be some edge cases but I want to get your feedback on this. What I did was create a similar function to `is_block_supported_at` called `is_multiblock_supported_at` in the `block.rs` to check for the next block (if it's free or not). 

Here's what the code looks like 
```rust 
pub fn is_multiblock_supported_at(block_id: BlockId, game: &Game, pos: BlockPosition) -> bool {
    match block_id.simplified_kind() {
        SimplifiedBlockKind::WoodenDoor | SimplifiedBlockKind::IronDoor => {
            match game.block_at(pos.up()){
                Some(block) => {
                    return block.is_air();
                },
                None => return false,
            }
        },
        SimplifiedBlockKind::Bed => {
            match block_id.facing_cardinal() {
                Some(face) =>{
                    match face {
                        FacingCardinal::North => {
                            match game.block_at(BlockPosition{x: pos.x, y: pos.y, z: pos.z-1}) {
                                Some(next_block) => {
                                    return next_block.is_air();
                                },
                                None => return false,
                            }
                        },
                        FacingCardinal::South => {
                            match game.block_at(BlockPosition{x: pos.x, y: pos.y, z: pos.z+1}) {
                                Some(next_block) => {
                                    return next_block.is_air();
                                },
                                None => return false,
                            }
                            
                        },
                        FacingCardinal::West =>{
                            match game.block_at(BlockPosition{x: pos.x-1, y: pos.y, z: pos.z}) {
                                Some(next_block) => {
                                    return next_block.is_air();
                                },
                                None => return false,
                            }

                        },
                        FacingCardinal::East => {
                            match game.block_at(BlockPosition{x: pos.x+1, y: pos.y, z: pos.z}) {
                                Some(next_block) => {
                                    return next_block.is_air();
                                },
                                None => return false,
                            }
                        }

                    }
                }
                None => return false,
            }

        }
        _ => return false,
    }

    return false;
}
```

Then of course, we would only place if the block is supported.

```rust
// handle multi-block placements (i.e. doors and beds)
        if is_multiblock_supported_at(block, game, pos) {
            if let Some((other_pos, other_block)) = match block.simplified_kind() {
                SimplifiedBlockKind::Bed => {
                    let mut head = block;
                    head.set_part(Part::Head);
                    Some((pos + block.facing_cardinal().unwrap().offset(), head))
                }
                SimplifiedBlockKind::IronDoor | SimplifiedBlockKind::WoodenDoor => {
                    let mut upper = block;
                    upper.set_half_upper_lower(HalfUpperLower::Upper);
                    Some((pos, upper))
                }
                _ => None,
            } {
                game.set_block_at(
                    world,
                    other_pos,
                    other_block,
                    BlockUpdateCause::Entity(player),
                );
            }
            game.set_block_at(world, pos, block, BlockUpdateCause::Entity(player));
        }
```

Sorry if the code is bad, I'm new to rust.

**Comment by Protonull** [comment]
Just compiled Feather and placed a door, it places correctly but it doesn't break correctly.
