### ISSUE TITLE
Connected blocks (Fences, walls, iron bars) do not connect

### ISSUE THREAD

**Issue by AnEthernetCable** [feather-rs/feather#295]
Any block that connects together such as Fences, Walls, Glass panes, and Iron bars do not properly connect together. See image below:
![image](https://user-images.githubusercontent.com/26227270/89827505-4e27ff00-db1d-11ea-9097-98a1a9e06d88.png)
This is as of commit `5e22d74` on Jul 31, 2020
Built and tested on Pop OS 20.04 + Linux kernel 5.4.0-7634-generic

**Comment by lolgeny** [comment]
Is anyone doing this already? If not I'll try

**Comment by amberkowalski** [comment]
This issue is not relevant at this point in time

**Comment by amberkowalski** [comment]
Closed - Blocks can't be placed right now at all so we can open a new issue if it this behavior happens again in the future.

**Comment by OxKitsune** [comment]
@lolgeny I advise you to join the discord, we can discuss issues easily there. Most issues that are listed here are no longer relevant due to a "rewrite".
