### ISSUE TITLE
Feather ecosystem and plugins

### ISSUE THREAD

**Issue by Defman** [feather-rs/feather#308]
For a feather to have a functional ecosystem there need to a few well-maintained plugins that the community can rely on. Theres two options we support the BukkitAPI or we release these plugins at the release of Feather. 

A few plugins, that I can think of
- Permission
- Subset of Essentials
- Subset of WorldGuard
- Subset of WorldEdit

Feel free to submit any suggestions.

**Comment by InitLad** [comment]
Might as well add a holograms plugin & a towny-like / factions-like plugin or some form of factions / nation plugin.
