### ISSUE TITLE
Memory leak somewhere 

### ISSUE THREAD

**Issue by TheUserCreated** [feather-rs/feather#325]
I'm not exactly sure where this leak is, but I get the sense it is in the way chunks are either generated or loaded.

Steps to reproduce:

start a new server & new world, watching the memory usage of feather server process
explore and generate new chunks, try flying far away
note that the memory usage does not decrease (seems to not unload chunks from memory?)

Even upon all players logging out, the memory usage does not appear to decrease

**Comment by caelunshun** [comment]
Fixed now that #307 is merged! Thanks for reporting.
