### ISSUE TITLE
Build script makes cargo rebuild each time when used as lib

### ISSUE THREAD

**Issue by LordMZTE** [feather-rs/feather#326]
I use `feather-network` as a dependency in my project like this `feather-network = { git = "https://github.com/feather-rs/feather.git", tag = "v0.6.0" }`. However, each time I run `cargo build` or `cargo check`, feather is rebuilt. This makes development painstakingly slow. It appears that this is caused by [this build script](https://github.com/feather-rs/feather/blob/v0.6.0/data/build.rs) which redownloads files on each build.

**Comment by caelunshun** [comment]
`feather-data` was removed in #307, so this should be fixed now :)
