### ISSUE TITLE
Placed blocks disappear after leave and rejoin...

### ISSUE THREAD

**Issue by XfedeX** [feather-rs/feather#330]
How to reproduce:
Place any block.
Leave server.
Join server again.

**Comment by Schuwi** [comment]
Are you sure this affects all block types? Which ones did you test it with?

**Comment by PunkmeisterDuy** [comment]
Did the server have write access? I had a similar problem, not with Feather, but in regular minecraft servers where if the server didnt have write perms, no changes would happen.

**Comment by Defman** [comment]
Well block placement haven't been implemented. This is the expected behavior at this stage of development.

**Comment by caelunshun** [comment]
> Well block placement haven't been implemented. This is the expected behavior at this stage of development.

Block placement is implemented on `develop`. There is another problem here.
