### ISSUE TITLE
[QUESTION] Plugin Support?

### ISSUE THREAD

**Issue by Technisha** [feather-rs/feather#340]
Heya! Just curious if plugins are working currently! (And a small side-question, do most vanilla mechanics work/can they be implemented with the plugin system if it exists?)
Thanks!

**Comment by Rheydskey** [comment]
#309

**Comment by aramperes** [comment]
There's a few tickets regarding plugins. The general consensus is that either Wasm or LUA will be used.

* Discussion on implementing a plugin system: #106 and #309 
* On a plugin ecosystem: #308 
* On a Bukkit compatibility layer: #236 

Not all vanilla features are implemented, for example entity AI. There's an approximate list of supported features in the README.

**Comment by Technisha** [comment]
Thanks! This clears things up for me!
