### ISSUE TITLE
Handle Held Item Change

### ISSUE THREAD

**Issue by devmattrick** [feather-rs/feather#355]
Right now, feather has no way of knowing what item a player is holding because it doesn't handle the packets for it. This prevents feather from knowing what blocks are being placed, which tools are being used, etc.

feather should keep track of which slot the player's cursor is on, which can then be used to determine which item is being held based on the inventory state.

I'm not entirely sure where the best place to store this state in. Window seems like a possible candidate but it also seems too generic for this. It may make sense to make another component (HeldItem?) and attach that to the player.

**Comment by caelunshun** [comment]
We had this functionality on the old `develop` branch, but it was lost in the 1.16 rewrite. We accomplished this using a `HeldItem` component as you suggested.

All that's needed to implement this is:
1. A new `HeldItem` component that contains a `usize`. It should encapsulate that field and ensure it's always in the range `0..9` (the range of valid hotbar indices).
2. Update the component when we receive the `HeldItemChange` packet.
