### ISSUE TITLE
Title messages

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#356]
https://minecraft.gamepedia.com/File:Title_command.png

Add support for sending title chat messages via plugins.

This entails:
1. Adding a new host call to [`quill-sys`](https://github.com/feather-rs/quill) called `entity_send_title` or similar.
2. Implement the host call in `feather-plugin-host`.
2. In `feather-common`, add a queue of title messages being sent to a player to the `ChatBox` component.
3. In `feather-server`, drain that queue each tick and send the `Title` packet.

**Comment by OxKitsune** [comment]
I'll take this one :)

**Comment by OxKitsune** [comment]
#403 Closes this issue.
