### ISSUE TITLE
Send plugin message packets in plugins

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#365]
Allow plugins to use the [plugin messaging system](https://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/). Critically, plugin messaging would allow plugins to transfer players to different proxy servers using the [BungeeCord plugin messaging API](https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/).

Steps to implement this:
1. Add a new host call called `plugin_message_send` to [`quill-sys`](https://github.com/feather-rs/quill).
2. Wrap the host call with a new method `Game::send_plugin_message(channel: &str, data: &[u8])` in `quill`.
3. Implement the host call in `feather-plugin-host` by triggering a new `PluginMessageEvent` (`game.ecs.insert_event`)
4. Add an event handler to `feather-server` that sends the `PluginMessage` packet to the client.
5. Test.

(For new contributors: I recommend reading [the architecture docs](https://github.com/feather-rs/feather/blob/main/docs/architecture.md) to get started.)

**Comment by dlee13** [comment]
I want to contribute, but I am lost on how to implement this. Please explain step 3. Do I need to define `PluginMessageEvent`? Where should it be?

**Comment by caelunshun** [comment]
> I want to contribute, but I am lost on how to implement this. Please explain step 3. Do I need to define `PluginMessageEvent`? Where should it be?

Yes, `PluginMessageEvent` should be defined in `feather-common`. It would look like
```rust
pub struct PluginMessageEvent {
    pub channel: String,
    pub data: Vec<u8>,
}
```

To send it to players in `feather-server`:
```rust
for (_, &client_id, event) in game.ecs.query::<(&ClientId, &PluginMessageEvent)>() {
    server.clients.get(client_id).unwrap().send_plugin_message(event.channel, event.data);
}
```

**Comment by dlee13** [comment]
Thanks, I have it implemented, so next is testing. Is there anything in particular you want in the test?

**Comment by caelunshun** [comment]
> Thanks, I have it implemented, so next is testing. Is there anything in particular you want in the test? I am actually not familiar with server administration, so now I am trying to learn how to configure BungeeCord.

It would be great to test it with BungeeCord. The setup is:
* Launch a BungeeCord instance
* Launch a Spigot instance
* Launch a Feather instance on a different port and set `proxy_mode = "bungee"` in `config.toml`
* Add both servers to the BungeeCord config
* Write a plugin that uses [this message](https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#connect) to transfer players to the Spigot server

If you like, you can submit a draft PR and we can test and review it :)

**Comment by dlee13** [comment]
I seem to be missing something/misunderstanding how the pieces are supposed to fit together, so I've opened up the draft PR.

**Comment by caelunshun** [comment]
All right, thanks! The implementation looks good to me; are you missing something about how to get the BungeeCord test setup to work?

**Comment by dlee13** [comment]
Yes, after reading through the wiki on the BungeeCord plugin messaging channel, I still didn't understand how to use it. I have BungeeCord and the servers configured though, and I understand how to compile plugins.

**Comment by caelunshun** [comment]
All right, makes sense. We need to send a plugin message with `channel` set to `"BungeeCord"` and the data encoded like this:
1. A `u16` containing the length of the command
2. The command (the string "connect" as bytes for this test)
3. A `u16` containing the length of the player's username
4. The player's username as bytes

The `u16`s can be encoded using the [`byteorder`](https://docs.rs/byteorder) crate (make sure to use `BigEndian`).
