### ISSUE TITLE
Support for native plugins

### ISSUE THREAD

**Issue by FeldrinH** [feather-rs/feather#383]
I gather from readme and issues about the plugin API that the plugin system will use a sandboxed wasm runtime.
Are there any plans to also support native plugins written in Rust and compiled to dylibs for plugins which are very performance intensive or require non-sandboxed system access for some reason (databases, complex inter-process communication, etc)?

**Comment by Defman** [comment]
DLibs are already supported, but we hope that in the future wasm and WASI get support for networking.

**Comment by FeldrinH** [comment]
Once wasm gets support for networking and is the plugin system is fully implemented on wasm, will support for dlibs remain, or are there plans to deprecate it?

**Comment by Defman** [comment]
There is "no difference" between writing WASM or DLibs plugins for the end developer. We have not decided if we are going to deprecate DLibs, but it might be ideal. If plugins need access to non-sandboxed features it would have to be handle through host calls. What kind of non-sandboxed features did you have in mind, that cannot be handle through networking or file descriptors?

**Comment by FeldrinH** [comment]
I was mainly concerned about performance loss due to the sandboxing, for plugins similar to for example CoreProtect, which tracks every block and tileentity change on the server and would consequently need to accept and process a lot of hooks with minimal overhead.

**Comment by Defman** [comment]
We can achieve near( 99.9%) native with WASM, the same overhead of copying applies to DLibs at the moment and should apply to prevent plugins from corrupting the server. It should be added that copying is very very cheap and does not affect performance in any meaningful way.
