### ISSUE TITLE
Support 1.8.9-latest

### ISSUE THREAD

**Issue by Milo123459** [feather-rs/feather#416]
# Feature Request

## Description

So the PvP aspect of the game definitely likes 1.8.9 and is a better version for pvp, so i think maybe allow feather to handle connections from clients on 1.8.9 to 1.16.5? I can help if need be

## What problem does this solve? What need does it fill?

Just will make feather more appealable

## Describe the solution you'd like

See above

**Comment by itsTyrion** [comment]
Maybe not 1.8.x, but slight multiversion. You can replicate large parts from the classic combat system in higher versions. I say that as a big 1.8.x player

**Comment by OxKitsune** [comment]
https://howoldisminecraft188.today/ I'm against 1.8.8 support. That version is super old and it's a pain to keep stuff working for it. The classic combat system is easily replicated on 1.16+ so I don't see the need to support these older versions. At least not right out of the box. Getting 1.16 combat working in the first place is a higher priority in my opinion.

**Comment by Defman** [comment]
How about modifying combat with plugins?

**Comment by Defman** [comment]
It should be handle by a proxy, in my opinion. (this would always be very very buggy)

**Comment by itsTyrion** [comment]
> 
> 
> https://howoldisminecraft188.today/ I'm against 1.8.8 support. That version is super old and it's a pain to keep stuff working for it. The classic combat system is easily replicated on 1.16+ so I don't see the need to support these older versions. At least not right out of the box. Getting 1.16 combat working in the first place is a higher priority in my opinion.

Yup. Multiversion in general for less antique versions may be worth considering in the distant future

**Comment by mainrs** [comment]
Have there been ideas on how this would be implemented? For example, if `feather` supports 1.12.x to 1.17.x, would that mean that the same binary could be used to run a server for any of the versions inside that range?

The protocol can differ quite a lot between versions. For a client like steverella it doesn't really matter as it barely does calculations and only draws stuff. But for the server this would mean to implement compatible block/entity/item behavior for each of the supported versions. This sounds like a lot of duplicate and boilerplate code to stick it all together.

**Comment by Bixilon** [comment]
I am also doing a ton of stuff with minecraft and I have gone through all versions. It is a big mess. The only version that is used is 1.8 and the latest (1.18.2). Everything between is only interesting for snapshot hunters or speed runners. Speed runners will never care about this project, they will always stick with vanilla.

The protocol changes so much, and that is only one problem. There are plenty of other problems, that you have to face with. Some of them:
 - What if older clients don't support game mechanics? (e.g. swimming). Is swimming then even possible?
 - Entities. The size changes (e.g. armor stands), that is unfair.
 - flattening (17w46a). All ids change, all names changes, ...
 - Entities again (like meta data index)
 - Items, Blocks. What if blocks don't, exist in previous versions? Should they be banned?


Yes, you could argue, that other projects are also doing it (e.g. via version), but it is hacky as f and I don't really support it. Multiversion only makes sense client sided, and even there it is highly questionable.


(And also imho this is really really really low priority)

**Comment by Milo123459** [comment]
Closing this due to it being something really not worth being done.
