### ISSUE TITLE
Missing "pull_request_template.md" under /docs/

### ISSUE THREAD

**Issue by WashingtonARamos** [feather-rs/feather#435]
[CONTRIBUTING.md](https://github.com/feather-rs/feather/blob/main/CONTRIBUTING.md#notes-to-your-code) says:

>## Notes to your code
>For notes to your code check the Checklist from [`pull_request_template.md`](docs/pull_request_template.md)

But said file is missing.

**Comment by OxKitsune** [comment]
Its located at  `.github/pull_request_template.md`

**Comment by FussballAndy** [comment]
Oh I moved it to .github/pull_request_template.md forgot there was a reference in CONTRIBUTING.md.
