### ISSUE TITLE
Is the project dead or in a stall state ?

### ISSUE THREAD

**Issue by nicolasvac** [feather-rs/feather#438]
Hi everyone, 

as the title says, is the project starting to get abandoned ?

Thank,
Nicolas.

**Comment by Miro-Andrin** [comment]
The projects contributions follows a pareto distribution.  Most lines of codes have been written by one person. That person only works on feather from time to time, so at times it seems like its dead. The project lacks experienced rust developers to even out the progress.

**Comment by amberkowalski** [comment]
Its not dead its just people are busy with life stuff rn or focused on the website.

Also wow rude smh

**Comment by nicolasvac** [comment]
Yeah, rust level to learn is actually pretty high at the moment.

Thank you both for the answers!

**Comment by SaabirMohamed** [comment]
This is an awesome project , I still use it and highly recommend it, 
IT MUST NEVER BE ABANDONED 
...currently(Aug 2021) trying to  integrate it in my kubenetes cluster.
I used HELM to spin up the mogodb replicas ...now just wana attach featherejs to that cluster ...and if it works It will be golden
