### ISSUE TITLE
Server with IPv6 address on Linux

### ISSUE THREAD

**Issue by qualterz** [feather-rs/feather#496]
## Description
On Windows the server with address `0.0.0.0` and port `25565`, which are defined in `config.toml`, automatically binds to the socket with address `[::]:25565`, but on Linux with the same configuration, the server binds to `0.0.0.0:25565`. If we change in `config.toml` address to `[::]`, we get a parse error. This makes it possible to connect to the server using only the IPv4 address.

**Comment by Defman** [comment]
This line https://github.com/feather-rs/feather/blob/3635ab54d38aeb94e0c1555b84bb7b204d1d2631/feather/server/src/config.rs#L81 should be changed to `IpAddr`.

**Comment by ambeeeeee** [comment]
We can close this now
