### ISSUE TITLE
Rewrite it in C

### ISSUE THREAD

**Issue by binex-dsk** [feather-rs/feather#530]
## Reproduction Steps

1. 
2. 
3. 
4. 

## Your Environment

- Operating System: 
- Operating System Version: 
- **Feather** Version:

**Comment by binex-dsk** [comment]
@caelunshun cringe. Not even being open to feature requests?

**Comment by Iaiao** [comment]
There's #suggestions on discord for feature requests like this.
![image](https://user-images.githubusercontent.com/55715058/151656186-26b17d62-4b6f-46ec-ad58-7a17862eee64.png)

**Comment by binex-dsk** [comment]
sneed
