### ISSUE TITLE
How to get to know the feather?

### ISSUE THREAD

**Issue by abzh423** [feather-rs/feather#542]
Is there any documentation on the architecture of feather or how it is built? I want to contribute in future and don't really understand anything.

**Comment by abzh423** [comment]
The project is pretty much dead or really quite for a while. 
Gob bless you.

**Comment by Titaniumtown** [comment]
gob

**Comment by abzh423** [comment]
> gob

Not anymore, not anymore. Nobody will ever know what we were talking about.

**Comment by abzh423** [comment]
> gob

![image](https://user-images.githubusercontent.com/81620918/157796913-aa8faa70-2a1a-442c-892d-18a0a3e93cc7.png)
Sexy stats bro

**Comment by Titaniumtown** [comment]
thank you lol
