### ISSUE TITLE
Entity position update event is always triggered each tick

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#81]
Thanks to this code:
https://github.com/caelunshun/feather/blob/25b98de2ec93fc4d7edabb2de36f5da658ac44e6/server/src/entity/component.rs#L75-L79

the `FlaggedStorage` containing entity positions is always marked as modified each tick. As a result, the server spams the client with 20 movement packets per entity per second, which causes the client to lag significantly when large quantities of entities are spawned.

slide-rs/specs#613 offers a way to bypass this by not triggering the position update event when the position is reset. However, it doesn't seem like this PR will be merged, so it seems necessary to implement our own version of `FlaggedStorage` with the capability to temporarily stop recording events.

**Comment by caelunshun** [comment]
The same happens with entity metadata packets:
https://github.com/caelunshun/feather/blob/25b98de2ec93fc4d7edabb2de36f5da658ac44e6/server/src/entity/metadata.rs#L78-L85

When metadata is sent, it is modified, causing the packet to be resent each tick.

As a temporary fix, I'm going to use the Specs fork from the mentioned PR. If it's not merged shortly, I'll write a library providing the specialized `FlaggedStorage`.

**Comment by caelunshun** [comment]
... and the same happens with velocities.

**Comment by caelunshun** [comment]
Right, I've fixed part of this.

Velocity packets continue to be sent for a short while after an item hits the ground. The physics system checks whether the velocity has changed before writing the event, and it turns out floating-point errors cause the velocity to change by minuscule amounts for a while until settling out at 0.0.

I'm not sure how to handle this—in fact, I don't even see if we should be sending entity velocity packets, since the client appears to figure this out on its own.

**Comment by momothereal** [comment]
> I don't even see if we should be sending entity velocity packets, since the client appears to figure this out on its own.

I think the client needs to receive the Velocity Packet when the change is not caused by physics. For example, if the velocity is changed due to being hit by a player (knockback), then the new velocity needs to be sent at the time of update.

**Comment by caelunshun** [comment]
Still happens with positions, too. Maybe there's some margin within which position updates don't have to be sent?

I tried loading a vanilla-generated world with Feather, but the client crashed because it was receiving ~700 packets per second for nearby entities. (How the client is unable to handle that but Feather gets by with 1% CPU usage is beyond me.)

**Comment by OvermindDL1** [comment]
The minecraft client (and server) implementations are not... at all efficient.  Lot of memory allocations on every-single-packet, lot of inefficient string hashmap lookups, some occasional reflection, etc...  It does a lot to send data 'slow enough' so not everything breaks.

**Comment by caelunshun** [comment]
After the Legion rewrite, this issue no longer exists.
